# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lucas Marques
title: Web FullStack Developer | Software Engineer
email: lucas.4.3@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  olucasmarquess
linkedin_username: lucas-marques

# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-user
  url: https://drive.google.com/file/d/10Z_kX_OlsNVyZyWNZNpduu5J1GQxWd51/view

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I'm passionate about technology, I believe that programming is much more than just writing codes.
  I'm 30 years old, I've been working with technology since I was 16. I have eight years of experience in web development, I graduated in Game Development, post-graduated in Software Engineering, and currently I am taking MBA in Project Management. I seek to see the world differently and solve problems quickly, always seeking to understand the needs of my clients. All the different experiences I had made me the unique professional I am today.

content:

  - title: Proficiency Stacks
    layout: text
    content: |
      - Ruby on Rails 7 years
      - JavaScript    5 years
      - React         3 years
      - Node          3 years
      - React Native  1 year
      - HTML5/SASS    6 years
      - Next JS       1 year
      - PostgreSQL    4 years
      - MongoDB       2 years
      - Docker        1 year

  - title: Strengths & Skills
    layout: text
    content: |
      -	Cloud Solutions(AWS, DigitalOcean, Heroku);
      -	Micro Services(Twilio, Stripe, Cloudinary);
      -	APIs (REST, GraphQL);
      -	Agile methodology(Scrum, Kanban);
      -	Tests (RSpec, MiniTest, Cypress);
      -	TypeScript;
      -	UX and UI;
      -	Design Patterns;
      -	Mentoring and leadership;
      -	Problem-solving, team worker, fast learner;
      -	Communicative, Creativity, empathetic, organized;

  - title: Contributions
    layout: text
    content: |
      - GraphQL (2022)
    url: https://github.com/virtualshield/rails-graphql

      - Torque Postgres (2021)
    url: https://github.com/crashtech/torque-postgresql

  - title: Experience
    layout: list
    content:
      - layout: left
        title: CTech(Software house company) (Full-time)
        sub_title: Web Full Stack Developer
        caption: Oct/2018 - Present
        description: |
            I developed and maintained some websites, systems, and applications for companies abroad(I worked with Rails on Rails, GraphQL, Javascript, React, PostgreSQL):
              -	It`s CheckMate (https://itsacheckmate.com) (API)
              -	SJN Journal(https://sjnjournal.com) (FrontEnd)
              -	JoinLoop (https://www.joinloop.com) (API)
              -	SubHQ (https://my.subhq.app/users/sign_in)(Front and Back)
              -	Enjoy(https://www.enjoy.com) (Backend)
              -	Smart Patients (https://www.smartpatients.com) (FrontEnd)
              -	VirtualShield (https://virtualshield.com) (Front and Back)
              -	Lawmatics(https://www.lawmatics.com) (Backend)


  - title:
    layout: list
    content:
      - layout: left
        title: VITS (Part-time)
        sub_title: Web Full Stack Developer
        caption: Oct/2018 - Jan/2023
        description: |
            -	As a partner, I could actively participate in a startup's routine in all aspects. I participated in all business decision-making, strategies plannings, and product development.
            -	I Developed an application with Ruby on Rails, Postgres, React, and Semantic UI, to help students to find teachers for English classes. I worked on that project from beginning to end.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
        title: Universidade Municipal de São Caetano do Sul
        caption: 01/2023 - 12/2023
        sub_title: Project Manager[MBA]

    # content:
    #     title: Pontifícia Universidade Católica de São Paulo
    #     caption: 06/2016 - 06/2018
    #     sub_title: Software Engineering[Post-Graduate]

    # content:
    #     title: Universidade Nove de Julho
    #     caption: 01/2011 - 12/2014
    #     sub_title: Game Development[Graduate]

  - title: Certification
    layout: text
    content: |
      - SFC - Scrum Fundamentals Certified - SCRUMstudy - 04/2023

  - title: Languages
    layout: text
    content: |
      - Portuguese (Native)
      - English (Full Professional Proficiency)


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
